### ISSUE TITLE
Pre-existing: Notification.tenant_id UUID vs Tenant.id VARCHAR(36) FK type incompatibility

### ISSUE THREAD

**Issue by ihoward40** [ihoward40/SintraPrime-Unified#291]
### Defect
The `Notification` model in `portal/routers/notifications.py` defines `tenant_id` as `UUID(as_uuid=True)` with a foreign key to `tenants.id`. However, the `Tenant` ORM model in `portal/models/user.py` defines `id` as `String(36)` (VARCHAR(36)).

### Evidence
PostgreSQL error when `Base.metadata.create_all()` is executed after all models are imported:
```
foreign key constraint "notifications_tenant_id_fkey" cannot be implemented
Key columns "tenant_id" and "id" are of incompatible types: uuid and character varying
```

### Root Cause
- `Tenant.id`: `String(36)` → PostgreSQL `VARCHAR(36)`
- `Notification.tenant_id`: `UUID(as_uuid=True)` → PostgreSQL `UUID`
- These types are incompatible for FK constraints in PostgreSQL

### Scope
- **Pre-existing**: NOT introduced by PR #290 (Option 5 Governed Activation)
- **NOT fixed by PR #290**: The PR's PostgreSQL certification tests were scoped to exclude this known mismatched table
- **Repository-wide PostgreSQL readiness**: This defect blocks repository-wide PostgreSQL certification
- **Option 5 scope**: Does NOT affect Option 5 certification, which only covers bootstrap-authority tables

### Remediation (not authorized in PR #290)
Either:
1. Change `Notification.tenant_id` from `UUID(as_uuid=True)` to `String(36)` to match `Tenant.id`, OR
2. Change `Tenant.id` from `String(36)` to `UUID(as_uuid=True)` to match `Notification.tenant_id` (broader impact — would affect all FK references to `tenants.id`)

### Discovered During
Option 5 PostgreSQL runtime certification (PR #290, commit `ce8665c0`). The PostgreSQL gate exposed this defect because SQLite tolerates type mismatches in FK columns but PostgreSQL does not.

**Comment by ihoward40** [comment]
## Expanded Forensic Evidence — Repository Identity/Schema Reconciliation

### Scope Upgrade

This issue is no longer merely a Notification FK mismatch. PR #290 forensic investigation proved it is a **repository-wide identity-type authority divergence** plus a **Notification schema divergence**.

### Proven Findings

**1. Identity-Type Authority Divergence**

| Layer | tenants.id | users.id | notifications.tenant_id | notifications.user_id |
|-------|-----------|---------|------------------------|----------------------|
| Raw SQL (`portal_schema.sql`) | UUID | UUID | UUID | UUID |
| ORM (`portal/models/`) | String(36) | String(36) | UUID(as_uuid=True) | UUID(as_uuid=True) |
| Migrations | TBD | TBD | TBD | TBD |

**2. Notification-Only String(36) Repair Failed**

PR #290 attempted to change `Notification.tenant_id` and `Notification.user_id` from `UUID(as_uuid=True)` to `String(36)` to match the ORM parent types. This was **disproven by PostgreSQL 16**:

```
column "tenant_id" is of type uuid
but expression is of type character varying
```

PostgreSQL rejects VARCHAR bind parameters against UUID columns. Changing only the Notification FK type does not solve the production schema — it moves the mismatch to the raw-SQL layer instead.

**3. Notification Column-Name Divergence**

| Layer | Column Name | Type |
|-------|------------|------|
| Raw SQL (`portal_schema.sql`) | `metadata` | JSONB |
| ORM (`portal/routers/notifications.py`) | `extra_data` | JSON |

The ORM attribute name does not match the raw-SQL column name.

**4. PR #290 Explicitly Excluded This Repair**

PR #290 returned all #291-specific changes to their prior state:
- `Notification.tenant_id` = `UUID(as_uuid=True)` (reverted)
- `Notification.user_id` = `UUID(as_uuid=True)` (reverted)
- `extra_data` attribute name restored (reverted)
- Experimental `test_orm_on_raw_sql_uuid_schema_compatibility` removed

The repair was deliberately deferred to this dedicated lane.

### Required Reconciliation Scope

1. Complete identity authority matrix for all entities (Tenant, User, Notification, Mission, Run, Principal, Approval, Matter, Case, Document, Agent, ServiceIdentity)
2. Inventory every FK targeting `tenants.id` and `users.id`
3. Determine actual production schema creation authority (ORM `create_all()` vs raw SQL bootstrap vs migrations)
4. Evaluate three strategies: UUID everywhere / String(36) everywhere / Dialect-aware canonical type
5. PostgreSQL 16 runtime certification (not SQLite-only)
6. Permanent identity/FK consistency gate to prevent future drift

### Stop Conditions

- Existing non-UUID IDs requiring remapping → Principal authorization required
- Destructive migration → Principal authorization required
- Public API contract change → Principal authorization required
- Authentication/tenant isolation semantics change → Principal authorization required

**Comment by ihoward40** [comment]
## SWARM-DOGFOOD-001 Evidence + Strategy C Architecture Decision

### Swarm Dogfood Result: PASS

5 independent swarm workers completed the first real engineering mission on the merged canonical swarm runtime:

```
SWARM_ID = SWARM-DOGFOOD-001
BASE_SHA = c15dc9b291b91e4adfb8b5d0de28db5a6dcd164b
WORKERS_REQUESTED = 5
WORKERS_STARTED = 5
WORKERS_COMPLETED = 5
WORKERS_FAILED = 0
VALID_ARTIFACTS = 5/5
MAX_SIMULTANEOUS_WORKERS = 5
HERMES_MANUAL_FALLBACK = FALSE
LEGACY_PROVIDER_DELEGATE_USED = FALSE
```

### Identity Authority Matrix (Swarm-Verified)

| Layer | tenants.id | users.id | notifications.tenant_id | notifications.user_id | notifications.id |
|-------|-----------|---------|------------------------|----------------------|-----------------|
| Raw SQL (portal_schema.sql) | UUID | UUID | UUID | UUID | UUID |
| ORM (portal/models/user.py) | String(36) | String(36) | N/A | N/A | N/A |
| ORM (portal/routers/notifications.py) | N/A | N/A | UUID(as_uuid=True) | UUID(as_uuid=True) | UUID(as_uuid=True) |
| PortableUUID | NOT USED | NOT USED | NOT USED | NOT USED | NOT USED |
| Default generator | str(uuid.uuid4()) | str(uuid.uuid4()) | uuid.uuid4() | uuid.uuid4() | uuid.uuid4() |
| API schema (Pydantic) | uuid.UUID | uuid.UUID | not in response | not in response | uuid.UUID |

### FK Scope (Expanded from Original Issue)

```
TENANT_FK_COUNT = 44 ORM / 42 SQL
USER_FK_COUNT = 58 ORM / 51 SQL
```

This is NOT a Notification-only repair. It is a repository-wide identity authority reconciliation.

### Notification Schema Divergence

| Layer | Column name | Type |
|-------|------------|------|
| Raw SQL | metadata | JSONB |
| ORM | extra_data | JSON |

### Key Findings

1. **PortableUUID already exists** in `portal/models/types.py` — dialect-aware TypeDecorator that stores native PostgreSQL UUID and SQLite-compatible String(36). Python always sees `uuid.UUID`.
2. **PortableUUID already used by 4 models**: legal_authority, blackstone, audit_record, evidence_snapshot
3. **Raw SQL is authoritative** — all identity columns in portal_schema.sql are already PostgreSQL UUID
4. **Prior Notification-only String(36) repair was disproven** by PostgreSQL 16 (VARCHAR bind to UUID column fails)
5. **All defaults generate UUIDs** — but historical data has NOT been proven to contain only UUIDs

### Architecture Decision: Strategy C — PortableUUID

```
RECOMMENDED_IDENTITY_STRATEGY = STRATEGY_C_PORTABLEUUID
PRINCIPAL_ARCHITECTURE_STOP = CLEARED
PRINCIPAL_DATA_STOP = CONDITIONAL

POSTGRESQL_STORAGE_TYPE = native UUID
SQLITE_STORAGE_TYPE = String(36)
PYTHON_IDENTITY_TYPE = uuid.UUID
API_IDENTITY_TYPE = uuid.UUID
CANONICAL_SQLALCHEMY_TYPE = PortableUUID (portal/models/types.py)
```

Use the EXISTING repository implementation. Do not create another UUID abstraction.

### Pre-Migration Data-Safety Gate (Mandatory)

Before changing deployed identity types, inspect every target database:
- `NON_UUID_ROWS = 0` required for every column being converted
- If any `NON_UUID_ROWS > 0`: MIGRATION = STOP, PRINCIPAL_STOP_REQUIRED = TRUE

### Corrected Classifications

```
PUBLIC_API_CHANGE_REQUIRED = FALSE (Strategy C preserves uuid.UUID in API)
NON_UUID_EXISTING_IDS_POSSIBLE = NOT_YET_PROVEN_FALSE (requires database inspection)
DESTRUCTIVE_MIGRATION_REQUIRED = FALSE (type-change-only, no data remapping)
RLS_CHANGE_REQUIRED = FALSE
AUTH_SEMANTICS_CHANGE = FALSE
```
