### ISSUE TITLE
chore(testing): evaluate pytest-timeout for local test safety

### ISSUE THREAD

**Issue by ihoward40** [ihoward40/SintraPrime-Unified#188]
Local full-suite pytest runs can exceed the operator tool timeout even when no test is hanging. Investigation showed the suite completes when protected with pytest-timeout and no individual test exceeded 120s.

## Proposed options

1. Add pytest-timeout to dev/test dependencies and configure a default timeout.
2. Keep pytest-timeout as a local-only operator tool.
3. Add a documented command for long local test runs instead of changing project dependencies.

## Acceptance criteria

- No production code changes.
- No Stripe changes.
- No dependency change unless separately approved.
- If implemented, update pyproject.toml and requirements.txt consistently.
- Confirm GitHub CI remains green.

## Evidence

- All root-level test files pass individually in under 60s.
- Combined suite passes with Error: 'Pillow' package not found. Install with: pip install Pillow
============================= test session starts =============================
platform win32 -- Python 3.14.0, pytest-9.1.0, pluggy-1.6.0
benchmark: 5.2.3 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: C:\Users\admin
plugins: anyio-4.12.1, asyncio-1.4.0, benchmark-5.2.3, cov-7.1.0, mock-3.15.1, timeout-2.4.0, typeguard-4.5.2
asyncio: mode=Mode.STRICT, debug=False, asyncio_default_fixture_loop_scope=None, asyncio_default_test_loop_scope=function
timeout: 120.0s
timeout method: thread
timeout func_only: False
collected 9279 items / 3438 errors / 3 skipped
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Users\admin\AppData\Local\pnpm\store\v10\projects\d8351c3c9860ad4aa048962d2c0442f1\skills-upstream\openclaw-skills\skills\ussyalfaks\near-qr-skill\near_qr.py", line 21, in <module>
INTERNALERROR>     from PIL import Image, ImageDraw, ImageFont
INTERNALERROR>   File "C:\Users\admin\AppData\Local\hermes\hermes-agent\venv\Lib\site-packages\PIL\Image.py", line 95, in <module>
INTERNALERROR>     from . import _imaging as core
INTERNALERROR> ImportError: cannot import name '_imaging' from 'PIL' (C:\Users\admin\AppData\Local\hermes\hermes-agent\venv\Lib\site-packages\PIL\__init__.py)
INTERNALERROR> 
INTERNALERROR> During handling of the above exception, another exception occurred:
INTERNALERROR> 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Python314\Lib\site-packages\_pytest\main.py", line 330, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>                          ~~~~^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Python314\Lib\site-packages\_pytest\main.py", line 383, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Python314\Lib\site-packages\pluggy\_hooks.py", line 512, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>            ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Python314\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Python314\Lib\site-packages\pluggy\_callers.py", line 167, in _multicall
INTERNALERROR>     raise exception
INTERNALERROR>   File "C:\Python314\Lib\site-packages\pluggy\_callers.py", line 139, in _multicall
INTERNALERROR>     teardown.throw(exception)
INTERNALERROR>     ~~~~~~~~~~~~~~^^^^^^^^^^^
INTERNALERROR>   File "C:\Python314\Lib\site-packages\_pytest\logging.py", line 803, in pytest_collection
INTERNALERROR>     return (yield)
INTERNALERROR>             ^^^^^
INTERNALERROR>   File "C:\Python314\Lib\site-packages\pluggy\_callers.py", line 139, in _multicall
INTERNALERROR>     teardown.throw(exception)
INTERNALERROR>     ~~~~~~~~~~~~~~^^^^^^^^^^^
INTERNALERROR>   File "C:\Python314\Lib\site-packages\_pytest\warnings.py", line 99, in pytest_collection
INTERNALERROR>     return (yield)
INTERNALERROR>             ^^^^^
INTERNALERROR>   File "C:\Python314\Lib\site-packages\pluggy\_callers.py", line 139, in _multicall
INTERNALERROR>     teardown.throw(exception)
INTERNALERROR>     ~~~~~~~~~~~~~~^^^^^^^^^^^
INTERNALERROR>   File "C:\Python314\Lib\site-packages\_pytest\config\__init__.py", line 1445, in pytest_collection
INTERNALERROR>     return (yield)
INTERNALERROR>             ^^^^^
INTERNALERROR>   File "C:\Python314\Lib\site-packages\pluggy\_callers.py", line 121, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Python314\Lib\site-packages\_pytest\main.py", line 394, in pytest_collection
INTERNALERROR>     session.perform_collect()
INTERNALERROR>     ~~~~~~~~~~~~~~~~~~~~~~~^^
INTERNALERROR>   File "C:\Python314\Lib\site-packages\_pytest\main.py", line 869, in perform_collect
INTERNALERROR>     self.items.extend(self.genitems(node))
INTERNALERROR>     ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Python314\Lib\site-packages\_pytest\main.py", line 1035, in genitems
INTERNALERROR>     yield from self.genitems(subnode)
INTERNALERROR>   File "C:\Python314\Lib\site-packages\_pytest\main.py", line 1035, in genitems
INTERNALERROR>     yield from self.genitems(subnode)
INTERNALERROR>   File "C:\Python314\Lib\site-packages\_pytest\main.py", line 1035, in genitems
INTERNALERROR>     yield from self.genitems(subnode)
INTERNALERROR>   [Previous line repeated 10 more times]
INTERNALERROR>   File "C:\Python314\Lib\site-packages\_pytest\main.py", line 1032, in genitems
INTERNALERROR>     rep, duplicate = self._collect_one_node(node, handle_dupes)
INTERNALERROR>                      ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Python314\Lib\site-packages\_pytest\main.py", line 895, in _collect_one_node
INTERNALERROR>     rep = collect_one_node(node)
INTERNALERROR>   File "C:\Python314\Lib\site-packages\_pytest\runner.py", line 589, in collect_one_node
INTERNALERROR>     rep: CollectReport = ihook.pytest_make_collect_report(collector=collector)
INTERNALERROR>                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Python314\Lib\site-packages\pluggy\_hooks.py", line 512, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>            ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Python314\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Python314\Lib\site-packages\pluggy\_callers.py", line 167, in _multicall
INTERNALERROR>     raise exception
INTERNALERROR>   File "C:\Python314\Lib\site-packages\pluggy\_callers.py", line 139, in _multicall
INTERNALERROR>     teardown.throw(exception)
INTERNALERROR>     ~~~~~~~~~~~~~~^^^^^^^^^^^
INTERNALERROR>   File "C:\Python314\Lib\site-packages\_pytest\fixtures.py", line 1797, in pytest_make_collect_report
INTERNALERROR>     result = yield
INTERNALERROR>              ^^^^^
INTERNALERROR>   File "C:\Python314\Lib\site-packages\pluggy\_callers.py", line 139, in _multicall
INTERNALERROR>     teardown.throw(exception)
INTERNALERROR>     ~~~~~~~~~~~~~~^^^^^^^^^^^
INTERNALERROR>   File "C:\Python314\Lib\site-packages\_pytest\capture.py", line 880, in pytest_make_collect_report
INTERNALERROR>     rep = yield
INTERNALERROR>           ^^^^^
INTERNALERROR>   File "C:\Python314\Lib\site-packages\pluggy\_callers.py", line 121, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Python314\Lib\site-packages\_pytest\runner.py", line 408, in pytest_make_collect_report
INTERNALERROR>     call = CallInfo.from_call(
INTERNALERROR>         collect, "collect", reraise=(KeyboardInterrupt, SystemExit)
INTERNALERROR>     )
INTERNALERROR>   File "C:\Python314\Lib\site-packages\_pytest\runner.py", line 361, in from_call
INTERNALERROR>     result: TResult | None = func()
INTERNALERROR>                              ~~~~^^
INTERNALERROR>   File "C:\Python314\Lib\site-packages\_pytest\runner.py", line 406, in collect
INTERNALERROR>     return list(collector.collect())
INTERNALERROR>                 ~~~~~~~~~~~~~~~~~^^
INTERNALERROR>   File "C:\Python314\Lib\site-packages\_pytest\python.py", line 564, in collect
INTERNALERROR>     self._register_setup_module_fixture()
INTERNALERROR>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
INTERNALERROR>   File "C:\Python314\Lib\site-packages\_pytest\python.py", line 577, in _register_setup_module_fixture
INTERNALERROR>     self.obj, ("setUpModule", "setup_module")
INTERNALERROR>     ^^^^^^^^
INTERNALERROR>   File "C:\Python314\Lib\site-packages\_pytest\python.py", line 290, in obj
INTERNALERROR>     self._obj = obj = self._getobj()
INTERNALERROR>                       ~~~~~~~~~~~~^^
INTERNALERROR>   File "C:\Python314\Lib\site-packages\_pytest\python.py", line 561, in _getobj
INTERNALERROR>     return importtestmodule(self.path, self.config)
INTERNALERROR>   File "C:\Python314\Lib\site-packages\_pytest\python.py", line 508, in importtestmodule
INTERNALERROR>     mod = import_path(
INTERNALERROR>         path,
INTERNALERROR>     ...<2 lines>...
INTERNALERROR>         consider_namespace_packages=config.getini("consider_namespace_packages"),
INTERNALERROR>     )
INTERNALERROR>   File "C:\Python314\Lib\site-packages\_pytest\pathlib.py", line 596, in import_path
INTERNALERROR>     importlib.import_module(module_name)
INTERNALERROR>     ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Python314\Lib\importlib\__init__.py", line 88, in import_module
INTERNALERROR>     return _bootstrap._gcd_import(name[level:], package, level)
INTERNALERROR>            ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
INTERNALERROR>   File "C:\Python314\Lib\site-packages\_pytest\assertion\rewrite.py", line 188, in exec_module
INTERNALERROR>     exec(co, module.__dict__)
INTERNALERROR>     ~~~~^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Users\admin\AppData\Local\pnpm\store\v10\projects\d8351c3c9860ad4aa048962d2c0442f1\skills-upstream\openclaw-skills\skills\ussyalfaks\near-qr-skill\test_near_qr.py", line 16, in <module>
INTERNALERROR>     from near_qr import (
INTERNALERROR>     ...<6 lines>...
INTERNALERROR>     )
INTERNALERROR>   File "C:\Users\admin\AppData\Local\pnpm\store\v10\projects\d8351c3c9860ad4aa048962d2c0442f1\skills-upstream\openclaw-skills\skills\ussyalfaks\near-qr-skill\near_qr.py", line 24, in <module>
INTERNALERROR>     sys.exit(1)
INTERNALERROR>     ~~~~~~~~^^^
INTERNALERROR> SystemExit: 1

========== 3 skipped, 31 warnings, 3438 errors in 982.10s (0:16:22) ===========.
- GitHub CI passes on the same main commit.
- Earlier local timeout was an operator/tool-runtime timeout, not a deadlock or regression.

Do not open a PR yet.
